import type { Metadata } from "next"
import { DM_Sans, Poppins } from "next/font/google"
import { Toaster } from "sonner"
import "./globals.css"
import Providers from "./providers"

const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

const dmSans = DM_Sans({
    variable: "--font-dm-sans",
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${dmSans.variable} ${poppins.variable} antialiased`}
            >
                <Providers>{children}</Providers>
                <Toaster position="top-center" richColors />
            </body>
        </html>
    )
}
