import type { Metadata } from "next"
import Navbar from "./_components/Navbar"

export const metadata: Metadata = {
    title: "Dashboard  -  Blog",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <>
            <Navbar />
            {children}
        </>
    )
}
