import type { Metadata } from "next"

export const metadata: Metadata = {
    title: "Login  -  Blog",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return <main className="h-app w-full relative">{children}</main>
}
